name: SupaKan
description: Instant task management platform built on Supabase with real-time collaboration, team chat, and AI assistance. Experience seamless Kanban boards, instant updates, and smart productivity insights - all with zero backend setup required.
repository: NubsCarson/SupaKan
website: https://supakan.nubs.site
category: Task Management
keywords:
  - task-management
  - kanban
  - real-time
  - supabase
  - react
  - typescript
  - ai
  - tailwindcss
  - vercel
  - shadcnui
  - team-collaboration
  - productivity
maintainers:
  - name: Nubs Carson
    email: nubs@nubs.site
    url: https://github.com/NubsCarson
support:
  email: nubs@nubs.site
  docs: https://supakan.nubs.site/docs
  community: https://github.com/NubsCarson/SupaKan/discussions
security:
  policy: https://github.com/NubsCarson/SupaKan/security/policy
  contact: nubs@nubs.site
funding:
  github: NubsCarson
  custom: https://supakan.nubs.site/sponsor
social:
  twitter: monerosolana